//! `#[derive(DuckEnum)]` 生成的 ENUM 读写所需的运行时工具，以及可选的「加载期建类型」。
//!
//! Runtime helpers used by the code generated by `#[derive(DuckEnum)]`, plus the optional
//! "create the type at load time" step.
//!
//! DuckDB 的 ENUM 由两部分组成：逻辑类型里存**标签字典**（`'red'` / `'green'` / `'blue'` …），
//! 向量数据里只存**下标**。所以读写只需要两件事：
//!
//! - 知道下标在向量里的物理宽度（[`enum_internal_type_for`]，按成员个数选 UTINYINT / USMALLINT /
//!   UINTEGER）；
//! - 用裸向量拿到下标数组（[`read_enum_index`] / [`write_enum_index`]，内部是
//!   `duckdb_vector_get_data`）。
//!
//! [`register_enum_type`] 则把「在 catalog 里建一个同名 ENUM 类型」这一步做成一行调用 ——
//! 它复用 SQL 宏的执行路径（[`register_sql_macro_str`](crate::register_sql_macro_str)，内部就是
//! `duckdb_query`），因此加载期执行 DDL 的机制与 `CREATE MACRO` 完全一致。
//!
//! A DuckDB ENUM is a label dictionary inside the logical type plus an index inside the vector, so
//! reading and writing only need two things: the physical width of the index (picked from the
//! member count) and the raw vector's index array. `register_enum_type` turns "create a type of the
//! same name in the catalog" into one call, reusing the SQL-macro execution path (which is
//! `duckdb_query` underneath).

use crate::register_sql_macro_str;
use crate::{DuckResult, duck_error};
use libduckdb_sys::{duckdb_vector, duckdb_vector_get_data};
use quack_rs::connection::Connection;
use quack_rs::prelude::TypeId;

/// ENUM 下标在向量里的物理宽度：DuckDB 按成员个数挑 `UTINYINT` / `USMALLINT` / `UINTEGER`。
///
/// 宽度由成员个数决定，而成员个数在编译期就已知，所以 `#[derive(DuckEnum)]` 生成的代码直接把它
/// 算出来，不必每次读取都去 `duckdb_vector_get_column_type` + `duckdb_enum_internal_type`
/// 取一次（那会为每个值分配并销毁一个逻辑类型）。
///
/// The physical width of an ENUM index: DuckDB picks `UTINYINT` / `USMALLINT` / `UINTEGER` from the
/// member count, which is known at compile time — so the derive computes it instead of asking the
/// vector for its column type on every value.
#[must_use]
pub fn enum_internal_type_for(member_count: usize) -> TypeId {
    match member_count {
        0..=255 => TypeId::UTinyInt,
        256..=65535 => TypeId::USmallInt,
        _ => TypeId::UInteger,
    }
}

/// 从向量的下标数组里读一个 ENUM 下标。
///
/// # Safety
///
/// 由宏生成的 `read_valid` 调用：`vector` 必须是本行所在列的裸向量，`row` 必须在该向量范围内。
///
/// Reads one ENUM index out of the vector's index array. Called from the macro-generated
/// `read_valid`; `vector` must be this row's column vector and `row` must be in range.
//
// 裸指针由 DuckDB FFI 提供，此处直接解引用
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn read_enum_index(vector: duckdb_vector, row: usize, member_count: usize) -> u32 {
    let data = unsafe { duckdb_vector_get_data(vector) };
    unsafe {
        match enum_internal_type_for(member_count) {
            TypeId::UTinyInt => u32::from(*data.cast::<u8>().add(row)),
            TypeId::USmallInt => u32::from(*data.cast::<u16>().add(row)),
            _ => *data.cast::<u32>().add(row),
        }
    }
}

/// 往向量的下标数组里写一个 ENUM 下标。
///
/// # Safety
///
/// 由宏生成的 `write_valid` 调用：`vector` 必须是本行所在列的裸向量，`row` 必须在该向量范围内。
///
/// Writes one ENUM index into the vector's index array. Called from the macro-generated
/// `write_valid`; `vector` must be this row's column vector and `row` must be in range.
//
// 裸指针由 DuckDB FFI 提供，此处直接解引用
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn write_enum_index(vector: duckdb_vector, row: usize, member_count: usize, index: u32) {
    let data = unsafe { duckdb_vector_get_data(vector) };
    unsafe {
        match enum_internal_type_for(member_count) {
            TypeId::UTinyInt => *data.cast::<u8>().add(row) = index as u8,
            TypeId::USmallInt => *data.cast::<u16>().add(row) = index as u16,
            _ => *data.cast::<u32>().add(row) = index,
        }
    }
}

/// 用双引号包住标识符，并把内部的 `"` 转义成 `""`。
///
/// Quotes an identifier, escaping inner `"` as `""`.
fn quote_identifier(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}

/// 用单引号包住字符串字面量，并把内部的 `'` 转义成 `''`。
///
/// Quotes a string literal, escaping inner `'` as `''`.
fn quote_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// 生成建 ENUM 类型的 SQL：`CREATE TYPE IF NOT EXISTS "name" AS ENUM ('a', 'b');`
///
/// 用 `IF NOT EXISTS` 而不是直接建：扩展可能被 `LOAD` 不止一次，重复执行不能报错；
/// 同时它也不会覆盖用户已有的同名类型。
///
/// Builds the `CREATE TYPE` statement. `IF NOT EXISTS` is used because an extension may be loaded
/// more than once — re-running must not fail — and it also leaves a pre-existing type untouched.
///
/// 注意标识符是**带引号**的，因此区分大小写；`#[derive(DuckEnum)]` 默认用小写蛇形名。
///
/// Note that the identifier is quoted and therefore case-sensitive; the derive defaults to a
/// lowercase snake_case name.
#[must_use]
pub fn enum_type_ddl(name: &str, members: &[&str]) -> String {
    let members = members
        .iter()
        .map(|member| quote_literal(member))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "CREATE TYPE IF NOT EXISTS {} AS ENUM ({});",
        quote_identifier(name),
        members
    )
}

/// 在 DuckDB 里建一个 ENUM 类型（幂等）。
///
/// 复用 SQL 宏那条执行路径（[`register_sql_macro_str`](crate::register_sql_macro_str)），
/// 所以它既能被 `#[duck_custom_register]` 调用，也能像 `#[derive(DuckEnum)]` 的
/// `create_type` 那样在加载期自动执行。语句用 `IF NOT EXISTS`，重复调用是安全的。
///
/// Creates an ENUM type in DuckDB, idempotently, through the same execution path the SQL macros
/// use. It can be called from `#[duck_custom_register]`, or automatically at load time by
/// `#[derive(DuckEnum)]`'s `create_type`.
///
/// ```ignore
/// #[duck_custom_register]
/// fn register_my_types(c: &Connection) -> DuckResult<()> {
///     duckfn::register_enum_type(c, "color", &["red", "green", "blue"])
/// }
/// ```
pub fn register_enum_type(connection: &Connection, name: &str, members: &[&str]) -> DuckResult<()> {
    if members.is_empty() {
        return Err(duck_error(format!(
            "cannot create ENUM type `{name}`: at least one member is required"
        )));
    }
    register_sql_macro_str(connection, &enum_type_ddl(name, members))
}
