//! 函数文档元数据的收集与导出。
//!
//! [`DuckFunctionDocItem`] 由 `#[duck_*]` 属性宏在编译期提交（写了 `description` /
//! `comment` / `example` 的才会提交），这里负责把它们收集起来、按函数名合并，并落成
//! community-extensions 文档页需要的 `function_descriptions.csv`。
//!
//! 为什么要绕这一圈：DuckDB 的 C 扩展 API 只暴露了 name / varargs / return_type /
//! volatile / special_handling 这些设置，**没有**设置 description 与 example 的接口，
//! 所以这类文本没法随扩展注册进 catalog。社区扩展的文档页由
//! `duckdb/community-extensions` 的 `scripts/generate_md.sh` 生成，它读扩展仓库里的
//! `docs/function_descriptions.csv`，再按 `function_name == other.function` LEFT JOIN
//! 覆盖 `functions` / `functions_overloads` 的展示列 —— 这份 CSV 是唯一的入口。
//!
//! Collection and export of the function documentation metadata. [`DuckFunctionDocItem`] is
//! submitted at compile time by the `#[duck_*]` attribute macros (only for functions that
//! actually carry `description` / `comment` / `example`); this module gathers them, merges
//! entries by function name and writes the `function_descriptions.csv` that the
//! community-extension doc pages consume.
//!
//! Why the detour: DuckDB's C extension API exposes only name / varargs / return_type /
//! volatile / special_handling — there is no way to set a function's description or examples,
//! so that text cannot reach the catalog through the extension itself. The community-extension
//! pages are generated by `scripts/generate_md.sh` in `duckdb/community-extensions`, which reads
//! `docs/function_descriptions.csv` and LEFT JOINs it on `function_name == other.function` to
//! override the display columns of `functions` / `functions_overloads` — this CSV is the only
//! way in.

use crate::{Connection, DuckResult, duck_error};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU32, Ordering};

/// `function_descriptions.csv` 的表头，与 `generate_md.sh` 里 `read_csv()` 读到的列名一致。
///
/// The header of `function_descriptions.csv`, matching the column names `read_csv()` sees in
/// `generate_md.sh`.
pub const CSV_HEADER: &str = "function,description,comment,example";

/// 打开导出开关的环境变量：它的值就是 CSV 的输出路径。
///
/// The environment variable that turns the export on; its value is the CSV's output path.
pub const DUMP_ENV_VAR: &str = "DUCKFN_DUMP_FUNCTION_DESCRIPTIONS";

/// 一条函数的文档元数据，由 `#[duck_*]` 宏通过 `inventory::submit!` 提交。
///
/// 字段用 `&'static str` / `&'static [&'static str]` 而不是 `String` / `Vec<String>`：
/// `inventory::submit!` 把值放进 `static` 初始化表达式（const 上下文），堆类型在那里
/// 构造不出来（与 [`crate::DuckScalarOverloadItem`] 的 `name` 同理）。
///
/// One function's documentation metadata, submitted by the `#[duck_*]` macros through
/// `inventory::submit!`. The fields are `&'static str` / `&'static [&'static str]` rather than
/// `String` / `Vec<String>` because `inventory::submit!` places the value in a `static`
/// initialiser (a const context), where heap types cannot be built (same reason as
/// [`crate::DuckScalarOverloadItem`]'s `name`).
pub struct DuckFunctionDocItem {
    /// 该函数在 DuckDB 里真正注册的名字（`overloads_name` 时是函数集名）。
    ///
    /// The name the function is really registered under (the function-set name when
    /// `overloads_name` is set).
    pub function: &'static str,
    /// 一句话说明。
    ///
    /// One-line summary.
    pub description: Option<&'static str>,
    /// 补充说明。
    ///
    /// Extra remarks.
    pub comment: Option<&'static str>,
    /// 调用示例。
    ///
    /// Usage examples.
    pub examples: &'static [&'static str],
}
// 把 `DuckFunctionDocItem` 登记进 inventory，供 [`declared_function_descriptions`] 遍历。
//
// Collect `DuckFunctionDocItem`s so that [`declared_function_descriptions`] can iterate over them.
inventory::collect!(DuckFunctionDocItem);

/// 合并后的函数文档：同一个函数名的多条提交（重载或函数集的各个签名）在这里合成一条。
///
/// A merged function description: several submissions under one function name (overloads, or the
/// signatures of one function set) collapse into a single entry here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FunctionDescription {
    /// 函数名（CSV 的 `function` 列）。
    ///
    /// The function name (the CSV's `function` column).
    pub function: String,
    /// 一句话说明（CSV 的 `description` 列）。
    ///
    /// One-line summary (the CSV's `description` column).
    pub description: Option<String>,
    /// 补充说明（CSV 的 `comment` 列）。
    ///
    /// Extra remarks (the CSV's `comment` column).
    pub comment: Option<String>,
    /// 调用示例；导出时用 `, ` 拼进 CSV 的 `example` 列。
    ///
    /// Usage examples; joined with `", "` into the CSV's `example` column on export.
    pub examples: Vec<String>,
}

/// 收集源码里声明的全部文档元数据，按函数名排序并合并。
///
/// 合并规则：`description` / `comment` 取第一个非空值，`examples` 拼接后按内容去重。
///
/// 只反映「写了文档参数的函数」：没写的不在这里。要拿到扩展真正注册进 catalog 的所有函数
/// （含手写注册与 SQL 宏）用 [`dump_function_descriptions_csv`]。
///
/// Collects every documentation entry declared in the source, sorted by function name and merged.
/// Merging takes the first non-empty `description` / `comment` and concatenates `examples` while
/// dropping duplicates. Only functions that carry documentation arguments appear here; for every
/// function the extension really registered (hand-written registrations and SQL macros included)
/// use [`dump_function_descriptions_csv`].
pub fn declared_function_descriptions() -> Vec<FunctionDescription> {
    let mut merged: BTreeMap<&'static str, FunctionDescription> = BTreeMap::new();
    for item in inventory::iter::<DuckFunctionDocItem>() {
        let entry = merged
            .entry(item.function)
            .or_insert_with(|| FunctionDescription {
                function: item.function.to_string(),
                description: item.description.map(str::to_string),
                comment: item.comment.map(str::to_string),
                examples: Vec::new(),
            });
        if entry.description.is_none() {
            entry.description = item.description.map(str::to_string);
        }
        if entry.comment.is_none() {
            entry.comment = item.comment.map(str::to_string);
        }
        for example in item.examples {
            if !entry.examples.iter().any(|existing| existing == example) {
                entry.examples.push((*example).to_string());
            }
        }
    }
    merged.into_values().collect()
}

/// 只按源码声明写出 `function_descriptions.csv`（不查 catalog）。
///
/// Writes `function_descriptions.csv` from the source declarations alone (the catalog is not
/// queried).
///
/// # Errors
///
/// 建目录或写文件失败时返回错误。
///
/// Returns an error when creating the parent directory or writing the file fails.
pub fn write_function_descriptions_csv(path: impl AsRef<Path>) -> DuckResult<()> {
    write_csv(path.as_ref(), &declared_function_descriptions())
}

/// 导出开关的目标路径；环境变量 [`DUCKFN_ENV_VAR`] 没设置时返回 `None`。
///
/// The export target path; `None` when the [`DUCKFN_DUMP_FUNCTION_DESCRIPTIONS`] environment
/// variable is not set.
pub(crate) fn dump_target() -> Option<PathBuf> {
    let value = std::env::var_os(DUMP_ENV_VAR)?;
    if value.is_empty() {
        return None;
    }
    Some(PathBuf::from(value))
}

/// 抓取当前 catalog 里的函数名快照（去重、有序）。
///
/// 让 DuckDB 自己把结果 `COPY` 到临时文件再读回来：duckfn 的列读取层是给函数回调用的
/// 内部抽象，为一个展示性的功能去扩它不划算。
///
/// Takes a snapshot of the function names currently in the catalog (deduplicated and ordered).
/// DuckDB writes the result to a temporary file with `COPY` and it is read back afterwards:
/// duckfn's column-reading layer is an internal abstraction for function callbacks, and growing it
/// for a presentational feature is not worth it.
///
/// # Errors
///
/// 查询或读临时文件失败时返回错误。
///
/// Returns an error when the query or reading the temporary file fails.
pub fn catalog_function_names(connection: &Connection) -> DuckResult<BTreeSet<String>> {
    let temp = temp_file_path();
    let result = copy_function_names(connection, &temp).and_then(|()| read_name_list(&temp));
    // 临时文件读不到就留着也无用，删不掉也不影响结果。
    //
    // The temporary file is useless once read; failing to delete it does not change the result.
    let _ = std::fs::remove_file(&temp);
    result
}

/// 注册完成后落盘：用注册前的快照差出「本扩展新增的函数」，再与源码声明的文档合并。
///
/// `before` 为 `None`（拿不到快照）时退化为「catalog 里的全部函数」，此时调用方应当已经在
/// stderr 上提示过。声明了文档、却没出现在 catalog 里的函数只警告、不写入。
///
/// Writes the file once registration has finished: the pre-registration snapshot is subtracted to
/// leave "the functions this extension added", which are then merged with the documentation
/// declared in the source. With `before == None` (no snapshot) this degrades to "every function in
/// the catalog"; the caller is then expected to have warned on stderr already. Functions that
/// declare documentation but never reached the catalog are only warned about, not written.
///
/// # Errors
///
/// 查询 catalog 或写文件失败时返回错误。
///
/// Returns an error when querying the catalog or writing the file fails.
pub fn dump_function_descriptions_csv(
    connection: &Connection,
    before: Option<&BTreeSet<String>>,
    path: impl AsRef<Path>,
) -> DuckResult<()> {
    let path = path.as_ref();
    let after = catalog_function_names(connection)?;
    let added: BTreeSet<String> = match before {
        Some(before) => after.difference(before).cloned().collect(),
        None => after,
    };
    let mut declared: BTreeMap<String, FunctionDescription> = declared_function_descriptions()
        .into_iter()
        .map(|row| (row.function.clone(), row))
        .collect();

    let mut rows = Vec::with_capacity(added.len());
    for name in &added {
        let row = declared.remove(name).unwrap_or_else(|| FunctionDescription {
            function: name.clone(),
            description: None,
            comment: None,
            examples: Vec::new(),
        });
        rows.push(row);
    }
    // 写了文档却没进 catalog：多半是 `auto_register = false`、名字拼错，或者注册失败。
    //
    // Documented but absent from the catalog: usually `auto_register = false`, a typo in the name,
    // or a failed registration.
    for missing in declared.keys() {
        eprintln!(
            "duckfn: `{missing}` declares documentation but is not registered in the catalog — \
             check `auto_register` and the function name"
        );
    }

    write_csv(path, &rows)?;
    let documented = rows.iter().filter(|row| row.description.is_some()).count();
    eprintln!(
        "duckfn: wrote {} function descriptions to {} ({} without a description)",
        rows.len(),
        path.display(),
        rows.len() - documented
    );
    Ok(())
}

/// 让 DuckDB 把 catalog 里的函数名写到一个临时 CSV。
///
/// Asks DuckDB to write the catalog's function names to a temporary CSV.
fn copy_function_names(connection: &Connection, path: &Path) -> DuckResult<()> {
    // 路径里可能有单引号；Windows 的反斜杠换成 `/`，DuckDB 两边都认，也免得被当成转义。
    //
    // The path may contain single quotes; Windows backslashes are rewritten to `/`, which DuckDB
    // accepts on every platform and which cannot be mistaken for an escape.
    let target = path.display().to_string().replace('\\', "/").replace('\'', "''");
    let sql = format!(
        "COPY (SELECT DISTINCT function_name FROM duckdb_functions() ORDER BY 1) \
         TO '{target}' (FORMAT csv, HEADER false)"
    );
    // SAFETY: `connection` 是 DuckDB 在初始化时交给扩展的有效连接，SQL 由本函数拼装。
    //
    // SAFETY: `connection` is the valid connection DuckDB hands to the extension at init time and
    // the SQL is assembled here.
    unsafe { connection.execute(&sql) }
        .map_err(|error| duck_error(format!("duckfn: cannot snapshot duckdb_functions(): {error}")))?;
    Ok(())
}

/// 读回 `copy_function_names` 写出的单列 CSV。
///
/// Reads back the single-column CSV written by [`copy_function_names`].
fn read_name_list(path: &Path) -> DuckResult<BTreeSet<String>> {
    let text = std::fs::read_to_string(path).map_err(|error| {
        duck_error(format!(
            "duckfn: cannot read the function-name snapshot {}: {error}",
            path.display()
        ))
    })?;
    // 函数名里不会有逗号，但 DuckDB 仍可能给带特殊字符的值加引号，剥掉更稳妥。
    //
    // Function names contain no comma, but DuckDB may still quote values with special characters,
    // so stripping the quotes is the safer read.
    Ok(text
        .lines()
        .map(|line| line.trim().trim_matches('"'))
        .filter(|line| !line.is_empty())
        .map(str::to_string)
        .collect())
}

/// 临时文件路径：进程号 + 自增序号，避免并发/重复调用互相覆盖。
///
/// Temporary-file path: pid plus a counter so concurrent or repeated calls cannot overwrite each
/// other.
fn temp_file_path() -> PathBuf {
    static COUNTER: AtomicU32 = AtomicU32::new(0);
    let seq = COUNTER.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!("duckfn_functions_{}_{seq}.csv", std::process::id()))
}

/// 按 RFC4180 写出 CSV：表头 [`CSV_HEADER`]，四个字段一行，LF 换行。
///
/// Writes the CSV following RFC 4180: the [`CSV_HEADER`] line, then one line of four fields per
/// function, with LF line endings.
fn write_csv(path: &Path, rows: &[FunctionDescription]) -> DuckResult<()> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(|error| {
                duck_error(format!(
                    "duckfn: cannot create {}: {error}",
                    parent.display()
                ))
            })?;
        }
    }

    let mut out = String::from(CSV_HEADER);
    for row in rows {
        out.push('\n');
        out.push_str(&csv_field(&row.function));
        out.push(',');
        out.push_str(&csv_field(row.description.as_deref().unwrap_or_default()));
        out.push(',');
        out.push_str(&csv_field(row.comment.as_deref().unwrap_or_default()));
        out.push(',');
        out.push_str(&csv_field(&row.examples.join(", ")));
    }
    out.push('\n');

    std::fs::write(path, out).map_err(|error| {
        duck_error(format!(
            "duckfn: cannot write {}: {error}",
            path.display()
        ))
    })
}

/// 单个 CSV 字段的转义：含 `,` `"` `\n` `\r` 时加引号并把 `"` 双写。
///
/// Escapes one CSV field: quoted, with inner `"` doubled, when it contains `,`, `"`, `\n` or `\r`.
fn csv_field(value: &str) -> String {
    if value.contains([',', '"', '\n', '\r']) {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}
