//! `#[derive(DuckEnum)]` 生成的 ENUM 读写所需的运行时工具。
//!
//! Runtime helpers used by the code generated by `#[derive(DuckEnum)]`.
//!
//! DuckDB 的 ENUM 由两部分组成：逻辑类型里存**标签字典**（`'red'` / `'green'` / `'blue'` …），
//! 向量数据里只存**下标**。所以读写只需要两件事：
//!
//! - 知道下标在向量里的物理宽度（[`enum_internal_type_for`]，按成员个数选 UTINYINT / USMALLINT /
//!   UINTEGER）；
//! - 用裸向量拿到下标数组（[`read_enum_index`] / [`write_enum_index`]，内部是
//!   `duckdb_vector_get_data`）。
//!
//! 「在 catalog 里建一个同名 ENUM 类型」在 [`crate::register_enum_type`]（见
//! [`named_types`](crate::value_types) 模块），它和 `#[derive(DuckStruct)]` 的
//! `create_type` 共用同一套 SQL 渲染与注册逻辑。
//!
//! A DuckDB ENUM is a label dictionary inside the logical type plus an index inside the vector, so
//! reading and writing only need the physical width of the index (picked from the member count) and
//! the raw vector's index array. Creating a named type of the same name is `register_enum_type`,
//! which shares its SQL rendering and registration with `#[derive(DuckStruct)]`'s `create_type`.

use libduckdb_sys::{duckdb_vector, duckdb_vector_get_data};
use quack_rs::prelude::TypeId;

/// ENUM 下标在向量里的物理宽度：DuckDB 按成员个数挑 `UTINYINT` / `USMALLINT` / `UINTEGER`。
///
/// 宽度由成员个数决定，而成员个数在编译期就已知，所以 `#[derive(DuckEnum)]` 生成的代码直接把它
/// 算出来，不必每次读取都去 `duckdb_vector_get_column_type` + `duckdb_enum_internal_type`
/// 取一次（那会为每个值分配并销毁一个逻辑类型）。
///
/// The physical width of an ENUM index: DuckDB picks `UTINYINT` / `USMALLINT` / `UINTEGER` from the
/// member count, which is known at compile time — so the derive computes it instead of asking the
/// vector for its column type on every value.
#[must_use]
pub fn enum_internal_type_for(member_count: usize) -> TypeId {
    match member_count {
        0..=255 => TypeId::UTinyInt,
        256..=65535 => TypeId::USmallInt,
        _ => TypeId::UInteger,
    }
}

/// 从向量的下标数组里读一个 ENUM 下标。
///
/// # Safety
///
/// 由宏生成的 `read_valid` 调用：`vector` 必须是本行所在列的裸向量，`row` 必须在该向量范围内。
///
/// Reads one ENUM index out of the vector's index array. Called from the macro-generated
/// `read_valid`; `vector` must be this row's column vector and `row` must be in range.
//
// 裸指针由 DuckDB FFI 提供，此处直接解引用
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn read_enum_index(vector: duckdb_vector, row: usize, member_count: usize) -> u32 {
    let data = unsafe { duckdb_vector_get_data(vector) };
    unsafe {
        match enum_internal_type_for(member_count) {
            TypeId::UTinyInt => u32::from(*data.cast::<u8>().add(row)),
            TypeId::USmallInt => u32::from(*data.cast::<u16>().add(row)),
            _ => *data.cast::<u32>().add(row),
        }
    }
}

/// 往向量的下标数组里写一个 ENUM 下标。
///
/// # Safety
///
/// 由宏生成的 `write_valid` 调用：`vector` 必须是本行所在列的裸向量，`row` 必须在该向量范围内。
///
/// Writes one ENUM index into the vector's index array. Called from the macro-generated
/// `write_valid`; `vector` must be this row's column vector and `row` must be in range.
//
// 裸指针由 DuckDB FFI 提供，此处直接解引用
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn write_enum_index(vector: duckdb_vector, row: usize, member_count: usize, index: u32) {
    let data = unsafe { duckdb_vector_get_data(vector) };
    unsafe {
        match enum_internal_type_for(member_count) {
            TypeId::UTinyInt => *data.cast::<u8>().add(row) = index as u8,
            TypeId::USmallInt => *data.cast::<u16>().add(row) = index as u16,
            _ => *data.cast::<u32>().add(row) = index,
        }
    }
}
