import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The docs are split into three sidebars, one per navbar entry:
 *
 * - `userGuide` — using duckfn: the root pages plus the `getting-started/`,
 *   `guide/` and `examples/` folders.
 * - `docsKit` — the `duckfn-docs-kit` tooling that builds a docs site like this one.
 * - `development` — the `development/` folder: working on the project itself.
 *
 * Pages keep the folder they are in, so their URLs stay stable. Inside a folder
 * the order still comes from `sidebar_position`; the three categories below are
 * spelled out because an `autogenerated` entry yields a folder's *contents*, not
 * the folder itself.
 */
const sidebars: SidebarsConfig = {
  userGuide: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        description:
          'Start from a template, learn the layout it uses, add duckfn, then call your first function from SQL.',
      },
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        description:
          'Everything duckfn can register: functions, macros, casts and replacement scans.',
      },
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'generated-index',
        description:
          "The repository's example extension, feature by feature, with runnable SQL.",
      },
      items: [{type: 'autogenerated', dirName: 'examples'}],
    },
    'duckdb-versions',
    'community-extension-docs',
    'faq',
    'known-issues',
  ],
  docsKit: [{type: 'autogenerated', dirName: 'docs-kit'}],
  development: [{type: 'autogenerated', dirName: 'development'}],
};

export default sidebars;